/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendita;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import tiendita.modelos.Cliente;
import tiendita.modelos.ControlCliente;
import tiendita.modelos.ControlFactura;
import tiendita.modelos.Factura;

/**
 *
 * @author Gerber
 */
public class frmFactura extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    ArrayList<Cliente> listaClientes = new ArrayList<Cliente>();
    ArrayList<Factura> listaFacturas = new ArrayList<Factura>();
    private boolean existeArchivoCliente = false;
    private boolean existeCliente = false;
    private double saldoDelCliente = 0.0;
    private double totalFactura = 0.0;
    static final double credito = 500.00;

    /**
     * Creates new form frmFactura
     */
    public frmFactura() {
        initComponents();
        cmbFormaPago.addItem("Efectivo");
        cmbFormaPago.addItem("Cheque");
        cmbFormaPago.addItem("Credito");
        this.lblSaldoRestante.setText(String.valueOf(credito));
    }

    public void configuracionInicial(String Nit, double totalDetalle, DefaultListModel detalleFactura) {
        this.totalFactura = 0.0;
        this.txtNitCli.setText(Nit);
        this.jListDetalleFactura.setModel(detalleFactura);
        consultarExisteCliente(Nit);
        totalFactura = totalDetalle;
        this.txtTotal.setText(String.valueOf(totalFactura));
    }

    private void consultarExisteCliente(String Nit) {
        listaClientes = ControlCliente.leerArchivo();
        if (listaClientes.isEmpty()) {
            this.lblMensajeAdvertencia.setVisible(true);
            this.existeArchivoCliente = false;
        } else {
            this.existeArchivoCliente = true;
            this.cliente = buscarCliente(Nit);
            if (this.cliente != null) {
                saldoDelCliente = credito - this.cliente.getDeudaCredito();
                this.existeCliente = true;
                this.txtNombreCli.setText(this.cliente.getNombre());
                this.txtNombreCli.setEnabled(false);
                this.txtDireccionCli.setText(this.cliente.getDireccion());
                this.txtDireccionCli.setEnabled(false);
                this.lblSaldoRestante.setText("Credito: Q " + String.valueOf(saldoDelCliente));
            } else {
                this.existeCliente = false;
            }
        }

    }

    private Cliente buscarCliente(String nit) {
        Cliente filtroCliente = listaClientes.stream()
                .filter(cli -> cli.getNit().equals(nit))
                .findAny()
                .orElse(null);
        return filtroCliente;
    }

    private boolean existArhivoFactura() {
        ArrayList<Factura> facturas = ControlFactura.leerArchivo();
        if (facturas.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        label1 = new java.awt.Label();
        txtNombreCli = new java.awt.TextField();
        label2 = new java.awt.Label();
        txtDireccionCli = new java.awt.TextField();
        label3 = new java.awt.Label();
        txtNitCli = new java.awt.TextField();
        label4 = new java.awt.Label();
        txtTotal = new java.awt.TextField();
        btnImprimirFact = new java.awt.Button();
        cmbFormaPago = new java.awt.Choice();
        label5 = new java.awt.Label();
        lblNoCheque = new java.awt.Label();
        txtNoCheque = new java.awt.TextField();
        lblNoCuenta = new java.awt.Label();
        txtNoCuenta = new java.awt.TextField();
        lblExisteCliente = new java.awt.Label();
        lblMensajeAdvertencia = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDetalleFactura = new javax.swing.JList<>();
        lblSaldoRestante = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label1.setText("Nombre:");

        label2.setText("Direción:");

        txtDireccionCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionCliActionPerformed(evt);
            }
        });

        label3.setText("Nit:");

        txtNitCli.setEditable(false);
        txtNitCli.setEnabled(false);

        label4.setText("Total");

        txtTotal.setEnabled(false);

        btnImprimirFact.setLabel("Facturar");
        btnImprimirFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimirFactMouseClicked(evt);
            }
        });
        btnImprimirFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirFactActionPerformed(evt);
            }
        });

        cmbFormaPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFormaPagoItemStateChanged(evt);
            }
        });

        label5.setText("Forma de pago:");

        lblNoCheque.setText("No. Cheque");

        txtNoCheque.setEditable(false);
        txtNoCheque.setEnabled(false);

        lblNoCuenta.setText("No. Cuenta");

        txtNoCuenta.setEditable(false);
        txtNoCuenta.setEnabled(false);

        lblExisteCliente.setBackground(new java.awt.Color(222, 222, 41));
        lblExisteCliente.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        lblExisteCliente.setText("Factura");

        lblMensajeAdvertencia.setForeground(new java.awt.Color(251, 0, 0));
        lblMensajeAdvertencia.setText("*Cliente no registrado");
        lblMensajeAdvertencia.setVisible(false);

        jScrollPane1.setViewportView(jListDetalleFactura);

        lblSaldoRestante.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lblSaldoRestante.setText("Credito: Q 500.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblExisteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMensajeAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNoCheque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                            .addComponent(txtNitCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDireccionCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombreCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(cmbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblSaldoRestante))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jScrollPane1))
                                    .addComponent(btnImprimirFact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExisteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDireccionCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNitCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFormaPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSaldoRestante, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimirFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionCliActionPerformed

    private void btnImprimirFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirFactMouseClicked
        // TODO add your handling code here:
        String mensaje = "";
        if (this.txtNombreCli.getText().equals("") || this.txtDireccionCli.getText().equals("")) {
            mensaje = "Asegurese de colocar Nombre o Dirección";
            mensajeError(mensaje);
        } else if ((this.cmbFormaPago.getSelectedItem() == "Credito") && (this.txtNoCuenta.getText().equals(""))) {
            mensaje = "Por favor ingrese el No. de cuenta del cliente";
            mensajeError(mensaje);
        } else if ((this.cmbFormaPago.getSelectedItem() == "Cheque") && this.txtNoCheque.getText().equals("")) {
            mensaje = "Por favor ingrese el No. de cheque del cliente";
            mensajeError(mensaje);
        } else {
            if (this.existeCliente) {
                this.agregarFactura();
            } else {
                this.agregarCliente();
                this.agregarFactura();
            }
        }
    }//GEN-LAST:event_btnImprimirFactMouseClicked

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(null,
                mensaje,
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    private void agregarCliente() {
        ArrayList<Cliente> clientes = new ArrayList<Cliente>();
        Cliente nuevoCliente = new Cliente();
        nuevoCliente.setNombre(this.txtNombreCli.getText().toString());
        nuevoCliente.setDireccion(this.txtDireccionCli.getText().toString());
        nuevoCliente.setNit(this.txtNitCli.getText().toString());
        if (this.cmbFormaPago.getSelectedItem() == "Credito") {
            nuevoCliente.setDeudaCredito(totalFactura);
        } else {
            nuevoCliente.setDeudaCredito(0.0);
        }
        clientes.add(nuevoCliente);
        if (this.existeArchivoCliente) {
            ControlCliente.agregarCliente(clientes);
        } else {
            ControlCliente.crearArchivo(clientes);
        }

    }

    private void agregarFactura() {
        Factura factura = new Factura();
        factura.setNit(this.txtNitCli.getText().toString());
        factura.setFormaPago(this.cmbFormaPago.getSelectedItem().toString());
        factura.setTotal(totalFactura);
        this.listaFacturas.add(factura);
        if (this.existArhivoFactura()) {
            ControlFactura.agregarFactura(listaFacturas);
        } else {
            ControlFactura.agregarFactura(listaFacturas);
        }
    }

    private void btnImprimirFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirFactActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnImprimirFactActionPerformed

    private void cmbFormaPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFormaPagoItemStateChanged
        // TODO add your handling code here:
        if (this.cmbFormaPago.getSelectedItem() == "Credito") {
            if (this.totalFactura > credito || (this.existeCliente && this.saldoDelCliente < this.totalFactura)) {
                String mensaje ="Crédito insuficiente...";
                mensajeError(mensaje);
                this.cmbFormaPago.remove("Credito");
            } else {
                this.txtNoCuenta.setText("");
                this.txtNoCuenta.setEnabled(true);
                this.txtNoCuenta.setEditable(true);
                this.txtNoCheque.setEnabled(false);
            }

        } else if (this.cmbFormaPago.getSelectedItem() == "Cheque") {
            this.txtNoCheque.setEnabled(true);
            this.txtNoCheque.setEditable(true);
            this.txtNoCuenta.setEnabled(false);
        } else {
            this.txtNoCheque.setEnabled(false);
            this.txtNoCuenta.setEnabled(false);
        }
    }//GEN-LAST:event_cmbFormaPagoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnImprimirFact;
    private java.awt.Choice cmbFormaPago;
    private javax.swing.JList<String> jListDetalleFactura;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label lblExisteCliente;
    private java.awt.Label lblMensajeAdvertencia;
    private java.awt.Label lblNoCheque;
    private java.awt.Label lblNoCuenta;
    private javax.swing.JLabel lblSaldoRestante;
    private java.awt.TextField txtDireccionCli;
    private java.awt.TextField txtNitCli;
    private java.awt.TextField txtNoCheque;
    private java.awt.TextField txtNoCuenta;
    private java.awt.TextField txtNombreCli;
    private java.awt.TextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
